import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/highLevel/navbar"

const funnelDisplay = Funnel_Display({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Vanshaj Kataria - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${funnelDisplay.className} antialiased bg-[#0b090a] text-[#d9d9d9]`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
